import Head from "next/head";
import Layout from "../components/layout/Layout";
import Posts from "../components/posts/Posts";
import ProtectedRoute from "../components/protectedRoute/ProtectedRoute";
import SharePost from "../components/sharePost/SharePost";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProtectedRoute>
        <Layout>
          <SharePost />
          <Posts />
        </Layout>
      </ProtectedRoute>
    </>
  );
}
